version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: hashbreaker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hashbreaker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hashbreaker"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hashbreaker-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: hashbreaker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hashbreaker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hashbreaker-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hashbreaker-rmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # port that python connect with RAMQ
      - "15672:15672" # UI port in the browser
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hashbreaker-network

  redis:
    image: redis:7-alpine
    container_name: hashbreaker-redis
    ports:
      - "6379:6379"
    networks:
      - hashbreaker-network

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: hashbreaker-redis-ui
    environment:
      - REDIS_HOSTS=local:hashbreaker-redis:6379
    ports:
      - "8081:8081"
    networks:
      - hashbreaker-network
    depends_on:
      - redis

volumes:
  postgres_data:

networks:
  hashbreaker-network:
    driver: bridge